const FoodTypes = [
  {
    id: 0,
    question: "What type of food would you like to eat?",
    answers: [
      "Afghan",
      "African",
      "American",
      "Arabian",
      "Argentine",
      "Australian",
      "Barbeque",
      "Brazilian",
      "Bistros",
      "Breakfast",
      "Brunch",
      "British",
      "Buffets",
      "Cajun",
      "Carribean",
      "Chicken Wings",
      "Chinese",
      "Comfort Food",
      "Cuban",
      "Curry",
      "Danish",
      "Dumplings",
      "Ethiopian",
      "Fast Food",
      "Filipino",
      "Fish & Chips",
      "French",
      "Gastropubs",
      "Gluten-Free",
      "German",
      "Greek",
      "Halal",
      "Hawaiian",
      "Hungarian",
      "International",
      "Indian",
      "Irish",
      "Italian",
      "Japanese",
      "Jewish",
      "Korean",
      "Kosher",
      "Kurdish",
      "Kebab",
      "Laotian",
      "Latin American",
      "Malaysian",
      "Mediterranean",
      "Mexican",
      "Middle Eastern",
      "Lebanese",
      "Moroccan",
      "New Zealand",
      "Nicaraguan",
      "Noodles",
      "Pakistani",
      "Polynesian",
      "Polish",
      "Portugese",
      "Pub Food",
      "Russian",
      "Rice",
      "Salad",
      "Sandwiches",
      "Scandinavian",
      "Schnitzel",
      "Seafood",
      "Singaporean",
      "Soul Food",
      "Soup",
      "Southern",
      "Spanish",
      "Steakhouses",
      "Taiwanese",
      "Thai",
      "Tex-Mex",
      "Turkish",
      "Ukranian",
      "Vegan",
      "Vegetarian",
      "Vietnamese",
      "Ramen",
      "Wok",
      "Wraps"
    ]
  }
];

export default FoodTypes;