const questionArray = [
  {
    id: 0,
    question: "What type of food would you like to eat?",
    answers: [
      "Afghan",
      "African",
      "American",
      "Arabian",
      "Argentine",
      "Australian",
      "Barbeque",
      "Brazilian",
      "Bistros",
      "Breaksfast",
      "Brunch",
      "British",
      "Buffets",
      "Cajun",
      "Carribean",
      "Chicken Wings",
      "Chinese",
      "Comfort Food",
      "Cuban",
      "Curry",
      "Danish",
      "Dumplings",
      "Ethiopian",
      "Fast Food",
      "Filipino",
      "Fish & Chips",
      "French",
      "Gastropubs",
      "Gluten-Free",
      "German",
      "Greek",
      "Halal",
      "Hawaiian",
      "Hungarian",
      "International",
      "Irish",
      "Italian",
      "Japanese",
      "Jewish",
      "Korean",
      "Kosher",
      "Kurdish",
      "Kebab",
      "Laotian",
      "Latin American",
      "Malaysian",
      "Mediterranean",
      "Mexican",
      "Middle Eastern",
      "Lebanese",
      "Moroccan",
      "New Zealand",
      "Nicaraguan",
      "Noodles",
      "Pakistani",
      "Polynesian",
      "Polish",
      "Portugese",
      "Pub Food",
      "Russian",
      "Rice",
      "Salad",
      "Sandwiches",
      "Scandinavian",
      "Schnitzel",
      "Seafood",
      "Singaporean",
      "Soul Food",
      "Soup",
      "Southern",
      "Spanish",
      "Steakhouses",
      "Taiwanese",
      "Thai",
      "Tex-Mex",
      "Turkish",
      "Ukranian",
      "Vegan",
      "Vegetarian",
      "Vietnamese",
      "Ramen",
      "Wok",
      "Wraps"
    ]
  },
  {
    id: 1,
    question: "What city do you live in?",
    answers: ["$20", "$50", "$100", "My Entire Paycheck"]
  },
  {
    id: 2,
    question: "How far are you willing to commute?",
    answers: [
      "Delivery Please",
      "0 miles",
      "5 miles",
      "10 miles",
      "15 miles",
      "20 miles",
      "25 miles"
    ]
  },
  {
    id: 3,
    question: "Is this casual or formal/celebratory?",
    answers: ["Casual", "Formal"]
  },
  {
    id: 4,
    question: "What is your budget?",
    answers: ["$20", "$50", "$100", "My Entire Paycheck"]
  },
  {
    id: 5,
    question: "ekajf",
    answers: ["$20", "$50", "$100", "My Entire Paycheck"]
  }
];

export default questionArray;
